language: node_js

node_js:
  - '4'

env:
  matrix:
    - BUILD='compat'     BROWSER='phantomjs'
    - BUILD='compat'     BROWSER='chrome'
    - BUILD='compat'     BROWSER='firefox'
    - BUILD='compat'     BROWSER='edge'
    - BUILD='compat'     BROWSER='opera12'
    - BUILD='compat'     BROWSER='safari9'
    - BUILD='compat'     BROWSER='safari8'
    - BUILD='compat'     BROWSER='safari7'
    - BUILD='compat'     BROWSER='safari6'
    - BUILD='compat'     BROWSER='ie11'
    - BUILD='compat'     BROWSER='ie10'
    - BUILD='compat'     BROWSER='ie9'
    - BUILD='compat'     BROWSER='ie8'
    - BUILD='compat'     BROWSER='ie7'

    - BUILD='nocompat'   BROWSER='phantomjs'
    - BUILD='nocompat'   BROWSER='chrome'
    - BUILD='nocompat'   BROWSER='firefox'
    - BUILD='nocompat'   BROWSER='edge'
    - BUILD='nocompat'   BROWSER='opera12'
    - BUILD='nocompat'   BROWSER='safari9'
    - BUILD='nocompat'   BROWSER='safari8'
    - BUILD='nocompat'   BROWSER='safari7'
    - BUILD='nocompat'   BROWSER='safari6'
    - BUILD='nocompat'   BROWSER='ie11'
    - BUILD='nocompat'   BROWSER='ie10'
    - BUILD='nocompat'   BROWSER='ie9'
    - BUILD='nocompat'   BROWSER='ie8'
    - BUILD='nocompat'   BROWSER='ie7'

    - BUILD='server'

  global:
    - secure: myFP8vndNuVGr2b+WtP4efJ2fJL7By7PUi2yxgbUlaqK82qgkayrp7zu6G7YKYBtWRTaRvwybX4XVZn9zCvFm2xTB8xSeWy3bB63JZcYPGzLpwusgJ69Kr+K5dAn/EzIj23pIjqVic9XmEEFK1FqCLp8V2Ty4kl3RG7onfwALUo=
    - secure: PFKH8/mY7hD82ipfa46znhWJQzEZ8226ZgHLVFLiM2LAxHP6aWGDgyYaSZVGlpulAGXx2Pq+RLPjetQRpjy7CA6NWr/2YtAxvx88QkufRRylKyNgEy5Pf1ej/V88SHnfdpGIizNeF/ofAMPmsGfBaDUm3+gU1RT+zLNj5gl3J/4=

matrix:
  include:
    - node_js: '0.12'
      env: BUILD='server'
    - node_js: '0.10'
      env: BUILD='server'

cache:
  directories:
    - node_modules

sudo: false
