language: node_js

node_js:
- 0.11

env:
  global:
  - secure: hxXNl/FkYm4lukIM+drQ4qXe6swmVyUvZRFhUCnMUZBTGsEHjySq/S1Z7KH69/3I+ULqERMeFo/Hsuw3fmZqtGwbFS+XyPm2ulCdhRy/ypCupSeTx/DbHV5Aej4QeGKb5J0N1jEEowMs5zTjpCoyNiSW/oFP/xS5tiuwUOvL+AQ=
  - secure: DdWSqy6Qzbnl3bTUIk+2oTEOghakK/UxtGow3ZUbzLxX9Lu924ve/7d+BQbJl+QsTqt+PYMPdpg6n7Y6oqOop6sAIRECPx/7lMx57whd0XHRXpLPbs2abXkFdG6w1x0ybm+6G2CiWUQ1BnmI1MqlkMmikK+X4jWgyJ7s1qYk4Us=

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - npm install -g grunt-cli

script:
  #- grunt test --reporters dots --browsers SL_Chrome
  - grunt --verbose default:travis